@extends('layouts.app')
@section('title', t($categoryTitle).' - '.site_setting('site_name', 'Skinoveda'))
@section('content')
@php
$serviceDetails = [
'laser-aesthetic'=>['✨','Advanced Laser & Aesthetic Care','Modern technology-led care for skin rejuvenation, pigmentation, acne scars, anti-aging, hair removal and face/body aesthetics.','https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1300&q=85',['Laser Hair Removal','Laser Skin Rejuvenation','Laser Toning','Carbon Laser Peel','Pigmentation & Melasma Care','Acne & Acne Scar Care','Open Pore Treatment','Skin Brightening','Anti-Aging','Skin Tightening','HIFU & RF','Face & Body Contouring','Non-Surgical Fat Reduction','PRP Hair Therapy']],
'hair-scalp'=>['🌿','Hair & Scalp Care','Personalized care for hair fall, scalp health, PRP support, dandruff and scalp rejuvenation.','https://images.unsplash.com/photo-1522338242992-e1a54906a8da?auto=format&fit=crop&w=1300&q=85',['Hair Fall Management','Hair Growth Support','PRP Hair Therapy','Scalp Rejuvenation','Dandruff & Scalp Care','Head & Scalp Therapy','Nutrition Guidance']],
'womens-intimate-wellness'=>['💜','Women’s & Intimate Wellness','Private, respectful and personalized wellness support for hormonal, fertility, intimate and reproductive care.','https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=1300&q=85',['Women’s Wellness Consultation','PCOS Wellness','Hormonal Wellness','Menstrual Wellness','Fertility Wellness','Infertility Support','Pre-Pregnancy Wellness','Post-Pregnancy Wellness','Menopause Wellness','Vaginal Rejuvenation','Pelvic Floor Wellness','Sexual Health & Wellness']],
'skin-dermatology'=>['🌸','Skin Health & Dermatology','Focused care for acne, melasma, pigmentation, scars, aging, texture and skin barrier concerns.','https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=1300&q=85',['Acne','Acne Scars','Melasma','Hyperpigmentation','Dark Spots','Uneven Skin Tone','Sensitive Skin','Dry Skin','Oily Skin','Enlarged Pores','Fine Lines & Wrinkles','Skin Rejuvenation','Skin Hydration & Barrier Care']],
'ayurveda-panchakarma'=>['🪷','Ayurveda & Panchakarma','Ancient Ayurvedic wisdom with personalized detox, rejuvenation and Panchakarma rituals.','https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1300&q=85',['Ayurvedic Consultation','Prakriti Assessment','Ayurvedic Nutrition','Panchakarma','Abhyanga','Shirodhara','Swedana','Nasya','Basti','Virechana','Pizhichil','Ayurvedic Detox','Rejuvenation Programs']],
'naturopathy-natural-therapy'=>['🍃','Naturopathy & Natural Therapy','Nature-led healing through lifestyle correction, detox programs, hydrotherapy, mud therapy and nutrition support.','https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1300&q=85',['Naturopathy Consultation','Natural Detox Programs','Therapeutic Diet Planning','Nutrition Guidance','Lifestyle Correction','Hydrotherapy','Sitz Bath Therapy','Mud Therapy','Steam Therapy','Herbal Therapy','Sleep & Stress Wellness']],
'holistic-health-lifestyle'=>['🩺','Holistic Health & Lifestyle','Lifestyle based wellness support for metabolic health, stress, sleep, digestive health and long term balance.','https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1300&q=85',['Diabetes Management Support','Weight Management','Obesity Management','PCOS Wellness','Digestive & Gut Wellness','Liver Wellness','Joint & Muscle Wellness','Stress & Sleep Wellness','Men’s Wellness','Women’s Hormonal Wellness']],
'detox-hijama-wellness'=>['🪷','Detox, Hijama & Wellness','Therapy-led wellness support including Hijama, cupping, acupuncture, acupressure, massage and detox rituals.','https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=1300&q=85',['Hijama Therapy','Wet Cupping','Dry Cupping','Cupping Therapy','Acupuncture Therapy','Acupressure','Reflexology','Therapeutic Massage','Ayurvedic Massage','Relaxation Therapy','Stress Relief Therapy']],
'facial-beauty'=>['🌸','Facial & Beauty','Premium skin and beauty rituals designed for glow, radiance, hydration and visible freshness.','https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=1300&q=85',['Royal Glow Facial','Skin Brightening','Hydration Ritual','Pearl Radiance Facial','Skin Polishing','Anti-Aging Facial','Barrier Repair Care','Beauty Consultation']],
'body-aesthetics'=>['✨','Body Aesthetics','Non-surgical support for body contouring, tightening, cellulite, abdomen, arm and thigh aesthetics.','https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1300&q=85',['Body Contouring','Non-Surgical Fat Reduction','Cellulite Care','Abdomen Contouring','Arm & Thigh Contouring','Body Skin Tightening','Face & Body Contouring']],
];
$detail = $serviceDetails[$activeCategory] ?? ['✦',$categoryTitle,'Personalized care category at Skinoveda.','https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1300&q=85',[]];
if (isset($serviceCategory) && $serviceCategory) {
    $detail[0] = $serviceCategory->icon ?: $detail[0];
    $detail[1] = $serviceCategory->headline ?: $detail[1];
    $detail[2] = $serviceCategory->short_description ?: $detail[2];
    $detail[3] = $serviceCategory->image ?: $detail[3];
    $detail[4] = array_values(array_filter((array) ($serviceCategory->focus_areas ?: $detail[4])));
}
$info = [
    'laser-aesthetic' => ['Best for visible skin, hair and body concerns where modern device-based care can support smoother texture, brighter tone and refined contours.','Your visit starts with skin assessment, concern mapping and a treatment plan. The expert will explain suitable laser or aesthetic options, expected sessions and aftercare.','Avoid harsh products before treatment, follow SPF guidance, and share any active skin sensitivity during consultation.'],
    'hair-scalp' => ['Best for hair fall, weak roots, dandruff, scalp imbalance and growth support.','We review scalp condition, lifestyle factors and hair goals before suggesting PRP support, scalp therapy or care routine.','Bring recent medical or hair history if available, and avoid heavy oil or styling products before scalp assessment.'],
    'womens-intimate-wellness' => ['Best for women looking for private support around PCOS, hormones, fertility, menopause, intimate wellness or reproductive health.','Consultation is handled respectfully in a confidential setting. Care plan may include wellness guidance, treatment support and follow-up.','You can share your concern comfortably. The team will guide the next step after understanding your history.'],
    'skin-dermatology' => ['Best for acne, melasma, pigmentation, dark spots, scars, pores, sensitive skin, dryness and texture issues.','Skin is assessed first, then care may include dermatology guidance, targeted treatments, facials or barrier repair planning.','Bring current skincare products or prescription history if possible, so the plan can be safer and more accurate.'],
    'ayurveda-panchakarma' => ['Best for people seeking Ayurvedic consultation, detox, rejuvenation, body balance and Panchakarma rituals.','The journey begins with Prakriti assessment and wellness consultation, followed by personalized therapy recommendations.','Eat light before therapy where advised, and discuss medical conditions before Panchakarma or detox programs.'],
    'naturopathy-natural-therapy' => ['Best for natural detox, lifestyle correction, stress, sleep, nutrition and preventive wellness support.','Consultation focuses on routine, food, sleep, stress and body signals, then a natural therapy plan is suggested.','Natural therapy works best with consistency, hydration, rest and simple lifestyle follow-through.'],
    'holistic-health-lifestyle' => ['Best for long-term wellness support around diabetes, weight, PCOS, digestion, liver, stress, sleep and lifestyle balance.','The expert looks at lifestyle patterns and health goals before suggesting a personalized wellness roadmap.','This is supportive wellness care. Bring any recent reports if you want a more informed consultation.'],
    'detox-hijama-wellness' => ['Best for therapy-focused wellness such as Hijama, cupping, acupuncture, massage, relaxation and detox support.','The therapist checks your need and comfort level first, then recommends the suitable therapy and session plan.','Hydrate well, eat appropriately before your appointment, and share any health condition before therapy.'],
    'facial-beauty' => ['Best for glow, hydration, freshness, skin polishing, radiance and premium beauty rituals.','Skin type and concern are checked before choosing the right facial or beauty ritual.','Avoid strong exfoliation before your session and follow the recommended home care after treatment.'],
    'body-aesthetics' => ['Best for body contouring, tightening, cellulite care and non-surgical fat reduction support.','Body goals and target areas are discussed first, then a realistic session plan is suggested.','Results depend on consistency, lifestyle and proper expert guidance.'],
][$activeCategory] ?? ['This service is designed for personalized care based on your concern.','Our expert will understand your need, explain options and guide a suitable care plan.','Share your history and goals during consultation for better guidance.'];
if (isset($serviceCategory) && $serviceCategory) {
    $info[0] = $serviceCategory->who_for ?: ($serviceCategory->overview ?: $info[0]);
    $info[1] = $serviceCategory->what_to_expect ?: $info[1];
    $info[2] = $serviceCategory->care_note ?: $info[2];
}
@endphp
<section class="service-detail-hero"><div class="container service-detail-grid"><div><span class="eyebrow">{{ t('Service Details') }}</span><h1><span>{{ $detail[0] }}</span> {{ t($categoryTitle) }}</h1><p>{{ t($detail[2]) }}</p><a href="#book-service" class="gold-button">{{ t('Book a slot →') }}</a></div><img src="{{ $detail[3] }}" alt="{{ t($categoryTitle) }}"></div></section>
<section class="service-detail-body"><div class="container service-detail-layout"><article class="service-detail-card"><h2>{{ t($detail[1]) }}</h2><p>{{ t($detail[2]) }}</p><div class="service-info-grid"><div><span>01</span><h3>{{ t('Who this is for') }}</h3><p>{{ t($info[0]) }}</p></div><div><span>02</span><h3>{{ t('What to expect') }}</h3><p>{{ t($info[1]) }}</p></div><div><span>03</span><h3>{{ t('Care note') }}</h3><p>{{ t($info[2]) }}</p></div></div><h3 class="service-mini-title">{{ t('Included focus areas') }}</h3>
<div class="service-detail-chip-list">
    @if(($focusAreas ?? collect())->isNotEmpty())
        @foreach($focusAreas as $focus)
            <a href="{{ route('treatments.focus', [$activeCategory, $focus->slug]) }}">{{ $focus->localized('name') }}</a>
        @endforeach
    @else
        @foreach($detail[4] as $item)
            <span>{{ t($item) }}</span>
        @endforeach
    @endif
</div>@if($treatments->isNotEmpty())<div class="service-admin-treatments"><h3>{{ t('Available treatments') }}</h3>@foreach($treatments as $treatment)<a href="{{ route('treatments.show', $treatment) }}"><strong>{{ t($treatment->name) }}</strong><small>{{ $treatment->duration_minutes }} {{ t('min') }} @if($treatment->price) · {{ t('BDT') }} {{ number_format($treatment->price) }} @endif</small></a>@endforeach</div>@endif</article><aside id="book-service" class="service-book-card"><span class="eyebrow !text-[#ac7b52]">{{ t('Book a slot') }}</span><h2>{{ t('Request appointment') }}</h2><form action="{{ route('appointments.store') }}" method="POST">@csrf<input type="hidden" name="category" value="{{ $activeCategory }}">@include('partials.focus-select')<label>{{ t('Full name') }}<input class="input" name="client_name" required></label><label>{{ t('Phone') }}<input class="input" name="phone" required></label><label>{{ t('Email') }}<input class="input" type="email" name="email" required></label><label>{{ t('Preferred date/time') }}<input class="input" type="datetime-local" name="appointment_at" required></label><label>{{ t('Preferred specialist') }}<select name="doctor_id" class="input"><option value="">{{ t('Any available expert') }}</option>@foreach($doctors as $doctor)<option value="{{ $doctor->id }}">{{ t($doctor->name) }} - {{ t($doctor->designation) }}</option>@endforeach</select></label><label>{{ t('Message') }}<textarea class="input" name="notes" rows="3" placeholder="{{ t($categoryTitle) }}"></textarea></label><button class="gold-button">{{ t('Book slot →') }}</button></form></aside></div></section>
@endsection
